version: "3.7"

services:
    # image project
    app:
        container_name: atm-app
        build:
            context: .
            dockerfile: Dockerfile
        image: tifabio/atm-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks: 
            - atmnetwork
    
    # nginx
    nginx:
        container_name: atm-nginx
        image: nginx:alpine
        restart: unless-stopped
        ports: 
            - "8080:80"
        volumes: 
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks: 
            - atmnetwork

    # db mysql
    mysql:
        container_name: atm-mysql
        image: mysql:5.7.32
        
        restart: unless-stopped
        environment: 
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes: 
            - ./.docker/mysql/dbdata:/var/lib/mysql
        networks: 
            - atmnetwork

networks: 
    atmnetwork:
        driver: bridge